# Makefile

# Define the binary name
BINARY_NAME=tasks

# Define the main package
MAIN_PACKAGE=./main.go

# Build the binary
build:
	go build -o $(BINARY_NAME) $(MAIN_PACKAGE)

# Run the binary
run: build
	./$(BINARY_NAME)

# Clean the binary
clean:
	rm -f $(BINARY_NAME)

# Install dependencies
deps:
	go mod tidy

# Run tests
test:
	go test ./...

# Phony targets
.PHONY: build run clean deps test